### ISSUE TITLE
What versions of Torch and CUDA are needed?

### ISSUE THREAD

**Issue by pzzmyc** [OedoSoldier/chatglm_webui#1]
Traceback (most recent call last):
  File "F:\AI\chatglm_webui\main.py", line 43, in <module>
    model = model.half().cuda()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

**Comment by Oyaxira** [comment]
```cmd
pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117
```
it's work for me

**Comment by alucardzhou** [comment]
I meet the same issue. and after running "pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117"
It shows another Error:
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.13.1+cu117

And I found a similar solution that fitting for my case:
"python -m pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117 --no-cache-dir "

Installing collected packages: torch, torchvision
  Attempting uninstall: torch
    Found existing installation: torch 1.13.1
    Uninstalling torch-1.13.1:
      Successfully uninstalled torch-1.13.1
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.14.1
    Uninstalling torchvision-0.14.1:
      Successfully uninstalled torchvision-0.14.1
Successfully installed torch-1.13.1+cu117 torchvision-0.14.1+cu117
source: https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/7166

Hope this tip could help someone like my case.

**Comment by pzzmyc** [comment]
I have just solved this issue by reinstalling Torch and CUDA. First, uninstall them and then reinstall them using the following command: "pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117".
